site_name: PyDFIRRam
site_url: https://PyDFIR.github.io/PyDFIRRam
site_description: Documentation for PyDFIRRam

repo_name: PyDFIRRam
repo_url: https://github.com/PyDFIR/PyDFIRRam

edit_uri: edit/main/docs/

theme:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  name: material
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.top
  icon:
    repo: fontawesome/brands/github

plugins:
  - mkdocstrings
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: PyDFIR/PyDFIRRam
      branch: main

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - index.md
  - Tutorials:
    - Installation : tutorials/installation.md
    - Windows : tutorials/windows.md
    - Linux/Mac : tutorials/linux.md
  - Reference:
    - Index: reference/reference.md
    - Base: reference/base.md
    - Handler: reference/handler.md
    - Renderer: reference/renderer.md
    - Utils: reference/utils.md
    - Windows : reference/windows.md
    - Testing : reference/test.md
  - Explanation:
    - Explanation : explanation/explanation.md
  - Guides:
    - Index: guide/guide.md
    - Testing : guide/test.md


extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PyDFIR/pyDFIRRam
      name: Github
    - icon: material/email
      link: "mailto:alexis.debrito@pm.me"