[tool.poetry]
name = "rampoetry"
version = "0.1.0"
description = ""
authors = ["Braguette <alexis.debrito@ecole2600.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
volatility3 = "^2.4.1"
pandas = "^2.0.3"
regex = "^2023.6.3"
typing-extensions = "^4.7.1"
pyarrow = "^12.0.1"
graphviz = "^0.20.1"


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
deptry = "^0.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
