[pytest]
testpaths = tests
addopts = -ra --maxfail=1 --strict-markers
markers =
    banners: volatility plugin test marker
    bigpools: volatility plugin test marker
    cachedump: volatility plugin test marker
    callbacks: volatility plugin test marker
    certificates: volatility plugin test marker
    cmdline: volatility plugin test marker
    configwriter: volatility plugin test marker
    crashinfo: volatility plugin test marker
    devicetree: volatility plugin test marker
    dlllist: volatility plugin test marker
    driverirp: volatility plugin test marker
    drivermodules: volatility plugin test marker
    driverscan: volatility plugin test marker
    dumpfile_physaddr: volatility plugin test marker
    dumpfile_pid: volatility plugin test marker
    dumpfile_virtaddr: volatility plugin test marker
    dumpfiles: volatility plugin test marker
    envars: volatility plugin test marker
    filescan: volatility plugin test marker
    getservicesids: volatility plugin test marker
    getsids: volatility plugin test marker
    handles: volatility plugin test marker
    hashdump: volatility plugin test marker
    hivelist: volatility plugin test marker
    hivescan: volatility plugin test marker
    hollowprocesses: volatility plugin test marker
    iat: volatility plugin test marker
    info: volatility plugin test marker
    joblinks: volatility plugin test marker
    malfind: volatility plugin test marker
    mbrscan: volatility plugin test marker
    memmap: volatility plugin test marker
    modscan: volatility plugin test marker
    modules: volatility plugin test marker
    mutantscan: volatility plugin test marker
    netscan: volatility plugin test marker
    netstat: volatility plugin test marker
    new: volatility plugin test marker
    poolscanner: volatility plugin test marker
    printkey: volatility plugin test marker
    privs: volatility plugin test marker
    pslist: volatility plugin test marker
    pslist_pid: volatility plugin test marker
    psscan: volatility plugin test marker
    pstree: volatility plugin test marker
    sessions: volatility plugin test marker
    ssdt: volatility plugin test marker
    statistics: volatility plugin test marker
    thrdscan: volatility plugin test marker
    threads: volatility plugin test marker
    vadinfo: volatility plugin test marker
    verinfo: volatility plugin test marker
    virtmap: volatility plugin test marker
    requires_dump: test requires a local memory dump file (set PYDFIRRAM_DUMP_FILE)
