[tox]
isolated_build = true
envlist = py310, lint

[gh-actions]
python =
    3.10: py310

[testenv]
description = Run test suite with pytest
deps =
    pytest>=7.2
    pytest-cov
    pandas>=2.2
    pyarrow>=15
passenv =
    PYDFIRRAM_DUMP_FILE
commands =
    python -m pytest tests {posargs:-ra --strict-markers}

[testenv:lint]
description = Validate packaging (Poetry)
skip_install = true
deps =
    poetry>=1.8.0
commands =
    poetry check
    poetry build
