name: build-mkdocs
on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Install required dependencies
      - run: pip install mkdocs mkdocs-material mkdocstrings[python] mkdocs-git-revision-date-localized-plugin mkdocs-git-committers-plugin-2 mike

      # Deploy the documentation
      - name: Deploy documentation
        run: |
          BRANCH=$(echo "${GITHUB_REF#refs/heads/}")
          if [ "$BRANCH" = "main" ]; then
            mike deploy --update-aliases latest
          elif [ "$BRANCH" = "dev" ]; then
            mike deploy dev
          fi
          mike deploy --push --clean
